export const filteredRegexes = [String.raw`\/+.+`,
    String.raw`\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}`,
    String.raw`\/+`,
    String.raw`/(?:\bip)/gmi`,
    String.raw`/(skibidi)/gmi`,
    String.raw`/(?:\bsigma)/gmi`,
    String.raw`/(nigger)/gmi`,
    String.raw`/(n.i.g.g.e.r)/gmi`,
    String.raw`/(nigga)/gmi`,
    String.raw`/(n.i.g.g.a)/gmi`,
    String.raw`/(?:\bOhio)/gmi`,
    String.raw`/(?:\bRizz)/gmi`,
    String.raw`/(?:\bzip packets)/gmi`,
]
